//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laghaee.WebSite {
    
    public partial class Attachment {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divUpload;
        protected System.Web.UI.WebControls.FileUpload FileUpload1;
        protected System.Web.UI.WebControls.FileUpload FileUpload2;
        protected System.Web.UI.WebControls.FileUpload FileUpload3;
        protected System.Web.UI.WebControls.FileUpload FileUpload4;
        protected System.Web.UI.WebControls.FileUpload FileUpload5;
        protected System.Web.UI.WebControls.Button BtnOk;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divGrdAttachment;
        protected System.Web.UI.WebControls.GridView gvAttachments;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divOperations;
        protected System.Web.UI.WebControls.Button btnOkDelAttach;
        protected System.Web.UI.WebControls.Button btnCancelAttach;
        protected System.Web.UI.WebControls.Button btnClose;
        protected System.Web.UI.WebControls.Label lblAttachMessage;
    }
}
