//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laghaee.WebSite {
    
    public partial class User {
        protected System.Web.UI.HtmlControls.HtmlGenericControl divOperations;
        protected System.Web.UI.WebControls.Button BtnNew;
        protected System.Web.UI.WebControls.Button BtnUpdate;
        protected System.Web.UI.WebControls.Button BtnRemove;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divDetail;
        protected System.Web.UI.WebControls.Label lblID;
        protected System.Web.UI.WebControls.TextBox txtID;
        protected System.Web.UI.WebControls.Label LblFirstName;
        protected System.Web.UI.WebControls.TextBox txtFirstName;
        protected System.Web.UI.WebControls.Label lblLastName;
        protected System.Web.UI.WebControls.TextBox txtLastName;
        protected System.Web.UI.WebControls.Label LblUserName;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.WebControls.Label LblPassword;
        protected System.Web.UI.WebControls.TextBox txtPassword;
        protected System.Web.UI.WebControls.Label LblEmailAddress;
        protected System.Web.UI.WebControls.TextBox txtEmailAddress;
        protected System.Web.UI.WebControls.CheckBoxList AccessPageCheckBoxList;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divGrid;
        protected System.Web.UI.WebControls.GridView grdUser;
    }
}
